module.exports.allowedUrls = [
  'https://praktikum.tk',
  'http://praktikum.tk',
  'http://localhost:3000',
  'http://localhost:3001',
  'https://mesto.edu.nomoredomains.xyz',
  'https://mesto.edu.nomoredomains.xyz/users',
  'https://mesto.edu.nomoredomains.xyz/cards',
  'https://mesto.edu.nomoredomains.xyz/users/me',
  'https://mesto.edu.nomoredomains.xyz/users/me/avatar',
  'https://api.mesto.edu.nomoredomains.xyz',
  'https://api.mesto.edu.nomoredomains.xyz/users',
  'https://api.mesto.edu.nomoredomains.xyz/cards',
  'https://api.mesto.edu.nomoredomains.xyz/users/me',
  'https://api.mesto.edu.nomoredomains.xyz/users/me/avatar',
];
